#!/bin/bash

rm PtokaX
rm core.*

gcc -std=c++11 -O2 -Wall -Wextra -o PtokaX \
 ./skein/Optimized_32bit/skein_block.c \
 ./skein/Optimized_32bit/skein.c \
 ./tinyxml/tinyxmlparser.cpp \
 ./tinyxml/tinyxmlerror.cpp \
 ./tinyxml/tinyxml.cpp \
 ./core/colUsers.cpp \
 ./core/DB-SQLite.cpp \
 ./core/DcCommands.cpp \
 ./core/DeFlood.cpp \
 ./core/eventqueue.cpp \
 ./core/ExceptionHandling.cpp \
 ./core/GlobalDataQueue.cpp \
 ./core/hashBanManager.cpp \
 ./core/hashRegManager.cpp \
 ./core/hashUsrManager.cpp \
 ./core/HubCommands.cpp \
 ./core/HubCommands-AE.cpp \
 ./core/HubCommands-FH.cpp \
 ./core/HubCommands-IQ.cpp \
 ./core/HubCommands-RZ.cpp \
 ./core/IP2Country.cpp \
 ./core/LanguageManager.cpp \
 ./core/LuaBanManLib.cpp \
 ./core/LuaCoreLib.cpp \
 ./core/LuaIP2CountryLib.cpp \
 ./core/LuaProfManLib.cpp \
 ./core/LuaRegManLib.cpp \
 ./core/LuaScript.cpp \
 ./core/LuaScriptManager.cpp \
 ./core/LuaScriptManLib.cpp \
 ./core/LuaSetManLib.cpp \
 ./core/LuaTmrManLib.cpp \
 ./core/LuaUDPDbgLib.cpp \
 ./core/ProfileManager.cpp \
 ./core/PtokaX-nix.cpp \
 ./core/PXBReader.cpp \
 ./core/pxstring.cpp \
 ./core/RegThread.cpp \
 ./core/ResNickManager.cpp \
 ./core/ServerManager.cpp \
 ./core/ServerThread.cpp \
 ./core/serviceLoop.cpp \
 ./core/SettingManager.cpp \
 ./core/TextConverter.cpp \
 ./core/TextFileManager.cpp \
 ./core/UdpDebug.cpp \
 ./core/UDPThread.cpp \
 ./core/UpdateCheckThread.cpp \
 ./core/User.cpp \
 ./core/utility.cpp \
 ./core/ZlibUtility.cpp \
 -I ./json \
 -I ./skein/Optimized_32bit \
 -I ./tinyxml \
 -I /usr/include/lua5.1 \
 -D_NDEBUG \
 -D_WITH_SQLITE \
 -DFLYLINKDC_USE_DB \
 -DUSE_FLYLINKDC_EXT_JSON \
 -DTIXML_USE_STL \
 -lstdc++ -pthread -ldl -lm -lz -llua -lsqlite3
