{
 "title": "FlylinkDC++ hub",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "flylinkdc_hub_users", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Chat messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "targets": [
    { "expr": "flylinkdc_hub_messages", "legendFormat": "Messages" }
   ]
  },
  {
   "title": "DirectConnect lua (messges/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(flylinkdc_hub_send_bytes[1m])",
     "legendFormat": "{{Try2Send}}"
    }
   ]
  },
  {
   "title": "DirectConnect cmd (messges/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(flylinkdc_hub_dc_commands_counter[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "DirectConnect lua (messges/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "rate(flylinkdc_hub_lua_commands_counter[1m])",
     "legendFormat": "{{func}}"
    }
   ]
  },
  {
   "title": "DirectConnect lua GetValue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "flylinkdc_hub_lua_user_value_counter",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "zlib",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "flylinkdc_hub_compress_bytes", "legendFormat": "{{bytes}}" }
   ]
  },
  {
   "title": "DirectConnect lua GetData",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "flylinkdc_hub_lua_user_value_counter",
     "legendFormat": "{{value}}"
    }
   ]
  }
 ]
}